name: build and deploy

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  buildAndRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yarn install and build
        run: |
          yarn
          yarn build
