name: build and deploy to prommerbua.github.io Repo

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  buildAndRun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yarn install and build
        run: |
          yarn
          yarn build
          yarn postbuild
          
      - name: Push to prommerbua.github.io repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: build/
          destination-github-username: 'Prommerbua'
          destination-repository-name: 'Prommerbua.github.io'
          user-email: michaelprommer@outlook.de
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
          
          
          
          
          
          

